[package]
name = "null_only_language"
version = "0.1.0"
authors = ["greg <greg.shuflin@protonmail.com>"]

[dependencies]

simplerepl = { path = "../simplerepl" }
llvm-sys = "*"
take_mut = "0.1.3"
itertools = "0.5.8"
getopts = "*"

