[package]
name = "rukka-lang"
version = "0.1.0"
authors = ["greg <greg.shuflin@protonmail.com>"]

[dependencies]
itertools = "0.5.8"
take_mut = "0.1.3"
llvm-sys = "*"

schala-repl = { path = "../schala-repl" }
