[package]
name = "schala-codegen"
version = "0.1.0"
authors = ["greg <greg.shuflin@protonmail.com>"]

[dependencies]
syn = { version = "0.13.1", features = ["full", "extra-traits"] }
quote = "0.5"

[lib]
proc-macro = true
